name: workflow
on: push 
jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: npm
      - run: make setup
      - run: make test
        with:
          uses: actions/upload-artifact@v3
      - run: make lint
        with:
          uses: actions/upload-artifact@v3